---
title: "Diversity and Distance analysis"
author: "Luyao Kang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include = F}
knitr::opts_chunk$set(
  collapse = T, echo = T, comment = "#>", message = F, warning = F,
	fig.align = "center", fig.width= 4.5, fig.height = 3, dpi = 150)
```
## Data input 
Set working and saving directory
```{r, message=FALSE}
setwd('e:/thermokarst_gully/')
save.dir <- file.path(getwd(),"result")
```
Loading packages
```{r}
pacman::p_load(phyloseq, ape, vegan, Biostrings, microbiome, tidyverse, rstatix)
```

### Test the difference in single function between control and collapsed groups using liner models
```{r}
# determine the effect size of the permafrost thawing for the diversity indexes
div_index <- c("Actinobacteria",	"Alphaproteobacteria",	"Acidobacteria",	"Firmicutes",	"Betaproteobacteria", "Planctomycetes",	"Gammaproteobacteria",	"Bacteroidetes",	"Deltaproteobacteria", "Ascomycota",	"Basidiomycota",	"Mortierellomycota", "Cercozoa",	"Conosa",	"Ciliophora",	"Chlorophyta",	"Apicomplexa",	"Ochrophyta",	"Pseudofungi",	"Lobosa",	"Sagenista",	"Opalozoa",	"Nematoda",	"Rotifera",	"Arthropoda",	"Annelida",	"Tardigrada", "Ric_N", "Ric_P", "Ric_S")

div_scale <- div_table %>% 
  select(c("Group", "Gully_id", div_index)) %>%
  mutate(across(where(is.numeric), scale)) %>%
  mutate(Group = factor(Group, levels = c("Control", "Collapsed"))) %>%
  select(where(~ !any(is.na(.))))

# codes for calculating the effect size refer to wu et al. 2022:https://github.com/Linwei-Wu/warming_soil_biodiversity.
div_S1 <- sapply(3:ncol(div_scale), function(j) {
    message("Now j=", j, " in ", ncol(div_scale), ". ", date())
    if (length(unique(div_scale[, j])) < 3) {
        result <- rep(NA, 10)
    } else {
        fm1 <- lmer(div_scale[, j] ~ Group + (1 | Gully_id), data = div_scale)

        presult <- car::Anova(fm1, type = 2)
        coefs <- coef(summary(fm1))[, "Estimate"]  ##four coefs
        names(coefs) <- paste0(names(coefs), ".mean")

        SEvalues <- coef(summary(fm1))[, "Std. Error"]  ##standard errors
        names(SEvalues) <- paste0(names(SEvalues), ".se")

        tvalues <- coef(summary(fm1))[, "t value"]  ##t values
        names(tvalues) <- paste0(names(tvalues), ".t")

        chisqP <- c(presult[, 1], presult[, 3])
        names(chisqP) <- c(paste0(row.names(presult), ".chisq"), paste0(row.names(presult), ".P"))

        result <- c(coefs, tvalues, SEvalues, chisqP)
    }
    result
})
colnames(div_S1)<-colnames(div_scale)[-c(1:2)]
data.frame(div_S1)
```


```{r, fig.align='center', fig.width=3.5, fig.height=7.8}
p.stars <- function(p.values) {
  unclass(symnum(p.values, corr = FALSE, 
                 na = FALSE, cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                 symbols = c("***", "**", "*", ".", " ")))}
single_div_comparison <- div_S1 %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column(., "variables") %>%
  mutate(sig = as.vector(unlist(lapply(Group.P, p.stars)))) %>%
  mutate(variables = factor(variables, levels = rev(div_index))) %>%
  mutate(colour = case_when(GroupCollapsed.mean <= 0 & Group.P <= 0.05 ~ "Negative",
                            GroupCollapsed.mean > 0 & Group.P <= 0.05 ~ "Positvie",
                            Group.P > 0.05 ~ "Neutral")) %>%
  ggplot(aes(x = variables, y = GroupCollapsed.mean, colour = colour)) +
  geom_hline(aes(yintercept = 0), size = 0.7,  colour = "gray2")+
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = GroupCollapsed.mean - GroupCollapsed.se, 
                    ymax = GroupCollapsed.mean + GroupCollapsed.se), 
                width = 0, position = position_dodge(width = 0.7), cex = 0.9) +
  geom_text(aes(label = sig, x = variables, y = (GroupCollapsed.mean/abs(GroupCollapsed.mean))*(abs(GroupCollapsed.mean) + GroupCollapsed.se)*1.2),
            position = position_dodge(0.1), vjust = 0.55) +
  labs(x = NULL, y = "Effect size") +
  scale_color_manual(values=c("blue", "grey", "red")) +
  scale_y_continuous(expand = c(0, 0), limit = c(-2, 2)) +
  theme_bw() + coord_flip() + scale_x_discrete(position = "top") +
  annotate("rect", xmin = 0.5, xmax = 3.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#ffffff") +
  annotate("rect", xmin = 3.5, xmax = 8.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#f19837") +
  annotate("rect", xmin = 8.5, xmax = 18.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#e56eee") +
  annotate("rect", xmin = 18.5, xmax = 21.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#5fb236") +
  annotate("rect", xmin = 21.5, xmax = 30.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#1ca9c9") +
  main_theme +
  theme(legend.position = "none",
        strip.background = element_rect(fill = c("#FFF6E1")),
        # axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

# if (!dir.exists(file.path(save.dir, "figs/env/"))) {
#   dir.create(file.path(save.dir, "figs/env/"))
# }
# ggsave(file.path(save.dir.multifunc, "./single_div_comparison.pdf"),
#        single_div_comparison, width = 2.7, height = 5, units = "in")
```

```{r, fig.align='center', fig.width=4.5, fig.height=6.5, message=FALSE}
### determine the average relative abundance of each phylum within each group
abun_table <- read.table(file = "E:/thermokarst_gully/data/multifun/multifun_abundance_table_all.csv",
             sep = ',',  header = T, row.names = 1, stringsAsFactors = F)
# determine the mean, standard deviations, standard errors for each phylum
taxa_name <- c("Actinobacteria",	"Alphaproteobacteria",	"Acidobacteria",	"Firmicutes",	"Betaproteobacteria", "Planctomycetes",	"Gammaproteobacteria",	"Bacteroidetes",	"Deltaproteobacteria", "Ascomycota",	"Basidiomycota",	"Mortierellomycota", "Cercozoa",	"Conosa",	"Ciliophora",	"Chlorophyta",	"Apicomplexa",	"Ochrophyta",	"Pseudofungi",	"Lobosa",	"Sagenista",	"Opalozoa",	"Nematoda",	"Rotifera",	"Arthropoda",	"Annelida",	"Tardigrada")

phyla_tabin_control <- abun_table %>%
  select(c("Group", taxa_name)) %>%
  mutate_if(is.numeric, ~ . * 100) %>%
  group_by(Group) %>% 
  summarise(across(where(is.numeric), list(mean = ~mean(., na.rm = T), 
                                           sd = ~sd(., na.rm = T), 
                                           n = ~n()))) %>% 
  pivot_longer(cols = -c(Group), 
               names_to = c('Phylum', '.value'), 
               names_sep = '_') %>% 
  mutate(se = sd/sqrt(n)) %>%
  filter(Group == "Control") %>%
  arrange(mean) %>%
  rbind(., data.frame(Group = c(rep("Control", 3)),
                      Phylum = c("Ric_N", "Ric_P", "Ric_S"), 
                      mean = c(rep(0, 3)), 
                      sd = c(rep(0, 3)), 
                      n = c(rep(30, 3)), 
                      se = c(rep(0, 3)))) %>%
    mutate(Phylum = factor(Phylum, levels = rev(div_index)))
  
  
avg_abun_in_control_plot <- phyla_tabin_control %>%
  ggplot(aes(x = Phylum, y = mean)) +
  geom_bar(position = 'dodge', stat = 'identity', 
           fill= '#FFF6E1', colour = 'black', width = 0.7) +
  geom_errorbar(aes(ymin = mean, ymax = mean + se), width=.2,  position = position_dodge(0.7)) +
  labs(x = NULL, y = 'Mean relative abundance (%)') +
  main_theme + coord_flip() + scale_y_reverse(limits=c(90, 0), expand=c(0, 0)) +
  annotate("rect", xmin = 0.4, xmax = 3.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#ffffff") +
  annotate("rect", xmin = 3.5, xmax = 8.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#f19837") +
  annotate("rect", xmin = 8.5, xmax = 18.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#e56eee") +
  annotate("rect", xmin = 18.5, xmax = 21.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#5fb236") +
  annotate("rect", xmin = 21.5, xmax = 30.5, ymin = 0, ymax = 90, alpha = 0.1, fill = "#1ca9c9") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank()
        )
```


```{r, fig.align='center', fig.width=5.5, fig.height=6.5}
library(aplot) # Decorate a 'ggplot' with Associated Information
diff_richness_abun_plot <- avg_abun_in_control_plot %>%
  insert_right(single_div_comparison, width = 1.5)
# ggsave(file.path(save.dir.comp, "./diff_comp_16s_plot.pdf"),
#        diff_comp_16s_plot, width = 4, height = 4.5, units = "in")
diff_richness_abun_plot
```

Composition
```{r}

```

