---
title: "Flux analysis"
author: "Luyao Kang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include = F}
knitr::opts_chunk$set(
  collapse = T, echo = T, comment = "#>", message = F, warning = F,
	fig.align = "center", fig.width= 4.5, fig.height = 3, dpi = 300)
```

## Data input
Set work directory
```{r}
setwd('e:/thermokarst_gully/')
save.dir <- file.path(getwd(),"result")
```

Loading packages
```{r}
pacman::p_load(tidyverse)
```

Data input
```{r}
source("script/read_data_rdp.R")
```

```{r}

```


Test the difference in flux between control and collapsed using linear mixed model. First is CO<sub>2</sub>:
```{r}
library(lme4)
library(car)
CO2_df <- flux_tab %>% filter(Flux_type == "CO2" & Time == "2023.8.18") %>%
  gather(key = "Group", value = "Flux_value", -c("Flux_type", "Time", "Gully_id", "Rep"))
fm1 <- lmer(Flux_value ~ Group + (1 | Gully_id), data = CO2_df)
summary(fm1)
car::Anova(fm1, type = 2)
```
Then, test the difference in CH<sub>4</sub>.
```{r}
library(lme4)
library(car)
CH4_df <- flux_tab %>% filter(Flux_type == "CH4" & Time == "2023.8.18") %>%
  gather(key = "Group", value = "Flux_value", -c("Flux_type", "Time", "Gully_id", "Rep"))
fm2 <- lmer(Flux_value ~ Group + (1 | Gully_id), data = CH4_df)
summary(fm2)
car::Anova(fm2, type = 2)
```
Finally, test the difference in N<sub>2</sub>O.
```{r}
library(lme4)
library(car)
N2O_df <- flux_tab %>% filter(Flux_type == "N2O" & Time == "2023.8.18") %>%
  gather(key = "Group", value = "Flux_value", -c("Flux_type", "Time", "Gully_id", "Rep"))
fm3 <- lmer(Flux_value ~ Group + (1 | Gully_id), data = N2O_df)
summary(fm3)
car::Anova(fm3, type = 2)
```

```{r, fig.align='center', fig.width=7.5, fig.height=3.5}
#load the packages
pacman::p_load(ggplot2, ggpubr, gghalves)
# set the main theme
main_theme = theme_bw() + 
  theme(panel.grid = element_blank(),
        panel.border = element_rect(size = 0.5),
        strip.text = element_text(colour = 'black', size = 6),
        strip.background = element_rect(colour = 'black', fill = 'grey'),
        axis.title = element_text(color = 'black',size = 6),
        axis.ticks = element_line(color = "black", linewidth = 0.5),
        axis.text.y = element_text(colour = 'black', size = 6),
        axis.text.x = element_text(colour = 'black', size = 6),
        legend.position = "none")
# set the contrast group for wilcox.test
my_comparisons <- list(c('Control', 'Collapsed'))
flux_names <- list(
  'CO2' = expression(paste("CO"[2], " (", mu, "mol", " m"^-2, " s"^-1, ")")),
  'CH4'= expression(paste("CH"[4], " (nmol", " m"^-2, " s"^-1, ")")),
  'N2O'= expression(paste("N"[2], "O", " (nmol", " m"^-2, " s"^-1, ")"))
)

# write a function to change the facet labels
facet_labeller <- function(variable,value){
  return(flux_names[value])
}

# plot
flux_plot <- flux_tab %>% 
  filter(Time == "2023.8.18") %>%
  select(c("Flux_type", "Gully_id", "Rep", "Control", "Collapsed")) %>%
  gather(key = "Group", value = "Flux_value", -c("Flux_type", "Gully_id", "Rep")) %>% 
  mutate(Flux_type = factor(Flux_type, levels = c("CO2", "CH4", "N2O"))) %>%
  mutate(Group = factor(Group, levels = c("Control", "Collapsed"))) %>%
  ggplot(aes(Group, Flux_value, fill = Group)) +
  geom_half_violin(position = position_nudge(x = 0.25), side = "r", width = 0.8, color = NA) +
  geom_boxplot(width = 0.4, size = 0.75, outlier.color = NA) +
  geom_jitter(aes(fill = Group), shape = 21, size = 1.5, width = 0.2) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  stat_compare_means(comparisons = my_comparisons, paired = F,
                     p.adjust.method = "BH", label = "p.signif", bracket.size = 0.3,
                     size = 3.5, tip.length = 0.00, method = "wilcox.test") +
  labs(x = NULL, y = NULL) +
  scale_fill_manual(values = c("#79ceb8", "#e95f5c", "#5cc3e8", "#ffdb00")) +
  facet_wrap(~Flux_type, scales = "free_y", ncol = 3, labeller = facet_labeller) +
  main_theme
if (!dir.exists(file.path(save.dir, "figs/flux/"))) {
  dir.create(file.path(save.dir, "figs/flux/"))
}
ggsave(file.path(save.dir, "./figs/flux/flux_plot.pdf"),
       flux_plot, width = 4.5, height = 2, units = "in")
flux_plot
```